version: '3.8'

services:
  app:
    # Локально открываем порт напрямую, чтобы заходить как localhost:8080
    ports:
      - "8080:8080"
    environment:
      # Локально можно переопределить настройки, если нужно
      SHOW_SQL: "true"

