spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/chat-db
        username: postgres
        password: new_password
    jpa:           
        show-sql: true
        hibernate:
            ddl-auto: create
    servlet:
      multipart:
        max-file-size: -1
        max-request-size: -1
file:
    upload-dir: uploads
